Repository ansible-collections/community.docker, pull requests merged in 2022-11, with the labels that each got.

#494 Fix non-matching defaults in docs
  plugins/modules/docker_network.py
  plugins/modules/docker_plugin.py
  plugins/modules/docker_volume.py
Labels: backport-1, backport-2

#487 docker_container: deprecate `ignore_image` and `purge_networks`
  changelogs/fragments/487-docker_container-deprecate.yml
  plugins/module_utils/module_container/module.py
  plugins/modules/docker_container.py
  tests/integration/targets/docker_container/tasks/tests/network.yml
  tests/integration/targets/docker_container/tasks/tests/options.yml
Labels: enhancement, docker-plain

#488 docker_container: add image_name_mismatch option
  changelogs/fragments/488-docker_container-image-name.yml
  plugins/module_utils/module_container/base.py
  plugins/module_utils/module_container/docker_api.py
  plugins/module_utils/module_container/module.py
  plugins/modules/docker_container.py
  tests/integration/targets/docker_container/tasks/tests/options.yml
Labels: enhancement, docker-plain

#509 Add docstring to ImageManager.__init__ and fix docstring for ImageManager.archive_image
  plugins/modules/docker_image.py
Labels: backport-2

#512 [stable-2] Make current_container_facts work with newer Docker versions and latest ansible-test container changes
  changelogs/fragments/510-current_container_facts.yml
  plugins/modules/current_container_facts.py
  tests/integration/targets/current_container_facts/aliases
  tests/integration/targets/current_container_facts/tasks/main.yml
Labels: backport-1

#500 Make image archive/save idempotent, using image id and repo tags as keys
  changelogs/fragments/500-idempotent-image-archival.yaml
  plugins/module_utils/image_archive.py
  plugins/modules/docker_image.py
  tests/integration/targets/docker_image/tasks/tests/options.yml
  tests/unit/plugins/module_utils/test_image_archive.py
  tests/unit/plugins/modules/test_docker_image.py
  tests/unit/plugins/test_support/docker_image_archive_stubbing.py
Labels: enhancement, docker-plain

#514 Handle ansible_default_ipv4 not there in tests
  tests/integration/targets/docker_config/tasks/test_docker_config.yml
  tests/integration/targets/docker_network/tasks/tests/ipam.yml
  tests/integration/targets/docker_network/tasks/tests/options.yml
  tests/integration/targets/docker_network/tasks/tests/overlay.yml
  tests/integration/targets/docker_secret/tasks/test_secrets.yml
  tests/integration/targets/docker_stack/tasks/test_stack.yml
  tests/integration/targets/docker_stack_info/tasks/test_stack_info.yml
  tests/integration/targets/docker_stack_task_info/tasks/test_stack_task_info.yml
Labels: backport-2
