Repository ansible-collections/community.docker, pull requests merged in 2023-01, with the labels that each got.

#549 Update CI matrix
  .azure-pipelines/azure-pipelines.yml
Labels: backport-2

#545 Add docker_container_copy_into module
  README.md
  changelogs/fragments/545-docker_api.yml
  meta/runtime.yml
  plugins/action/docker_container_copy_into.py
  plugins/connection/docker_api.py
  plugins/module_utils/_api/api/client.py
  plugins/module_utils/_scramble.py
  plugins/module_utils/copy.py
  plugins/modules/docker_container_copy_into.py
  tests/integration/targets/docker_container_copy_into/aliases
  tests/integration/targets/docker_container_copy_into/meta/main.yml
  tests/integration/targets/docker_container_copy_into/tasks/main.yml
  tests/integration/targets/docker_container_copy_into/tasks/run-test.yml
  tests/integration/targets/docker_container_copy_into/tasks/tests/content.yml
  tests/integration/targets/docker_container_copy_into/tasks/tests/file.yml
  tests/integration/targets/generic_connection_tests/tasks/main.yml
  tests/integration/targets/setup_docker_registry/tasks/setup-frontend.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/plugins/module_utils/test__scramble.py
  tests/unit/plugins/module_utils/test_copy.py
Labels: docker-plain

#556 [stable-2] docker_plugin: do not crash when plugin doesn't exist
  changelogs/fragments/553-docker_plugin-check-mode.yml
  plugins/modules/docker_plugin.py
  tests/integration/targets/docker_plugin/tasks/tests/basic.yml
Labels: backport-1

#555 [stable-2] Improve envvar fallback handling
  changelogs/fragments/554-env-vars.yml
  plugins/module_utils/common.py
Labels: backport-1

#560 docs: Fix json path in asserts
  plugins/modules/docker_compose.py
Labels: backport-1, backport-2

#563 Fix CI
  tests/utils/constraints.txt
Labels: backport-1, backport-2
